-- Credit Risk Intelligence Platform
-- Stage 2 Snowflake foundation
-- Purpose: create CURATED-layer tables for validated and cleaned credit risk cases.

USE DATABASE ML_RISK_CONTROL;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS CREDIT_RISK_CASES (
    CURATED_RECORD_ID VARCHAR NOT NULL,
    SOURCE_DATASET_SPLIT VARCHAR NOT NULL,
    SOURCE_SCHEMA_NAME VARCHAR NOT NULL DEFAULT 'RAW',
    SOURCE_TABLE_NAME VARCHAR NOT NULL,
    RAW_INGESTION_ID VARCHAR NOT NULL,
    SOURCE_FILE_NAME VARCHAR NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    DATASET_FINGERPRINT VARCHAR,
    CURATED_SCHEMA_VERSION VARCHAR NOT NULL,
    CURATED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IS_VALID_ROW BOOLEAN NOT NULL DEFAULT TRUE,
    HAS_DATA_QUALITY_WARNINGS BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_QUALITY_WARNING_SUMMARY VARCHAR,
    SOURCE_ROW_ID NUMBER(38,0),
    TARGET_SERIOUS_DLQIN_2YRS NUMBER(1,0),
    REVOLVING_UTILIZATION_UNSECURED_LINES FLOAT,
    AGE_YEARS NUMBER(38,0),
    DELINQUENCY_30_59_COUNT NUMBER(38,0),
    DEBT_RATIO FLOAT,
    MONTHLY_INCOME FLOAT,
    OPEN_CREDIT_LINES_AND_LOANS_COUNT NUMBER(38,0),
    TIMES_90_DAYS_LATE_COUNT NUMBER(38,0),
    REAL_ESTATE_LOANS_OR_LINES_COUNT NUMBER(38,0),
    DELINQUENCY_60_89_COUNT NUMBER(38,0),
    DEPENDENTS_COUNT FLOAT,
    AGE_IMPLAUSIBLE_FLAG BOOLEAN,
    REVOLVING_UTILIZATION_GT_1_FLAG BOOLEAN,
    DEBT_RATIO_GT_5_FLAG BOOLEAN,
    MONTHLY_INCOME_MISSING_FLAG BOOLEAN,
    MONTHLY_INCOME_NON_POSITIVE_FLAG BOOLEAN,
    DEPENDENTS_MISSING_FLAG BOOLEAN,
    DEPENDENTS_NEGATIVE_FLAG BOOLEAN,
    DELINQUENCY_EXTREME_FLAG BOOLEAN
)
COMMENT = 'Validated and cleaned credit risk cases with standardized field names, lineage metadata, and warning-level data quality flags.';
