-- Credit Risk Intelligence Platform
-- Stage 2 Snowflake foundation
-- Purpose: create FEATURES-layer tables for model-ready feature snapshots.

USE DATABASE ML_RISK_CONTROL;
USE SCHEMA FEATURES;

CREATE TABLE IF NOT EXISTS CREDIT_RISK_FEATURES (
    FEATURE_RECORD_ID VARCHAR NOT NULL,
    CURATED_RECORD_ID VARCHAR NOT NULL,
    SOURCE_DATASET_SPLIT VARCHAR NOT NULL,
    FEATURE_SCHEMA_VERSION VARCHAR NOT NULL,
    FEATURE_PIPELINE_VERSION VARCHAR NOT NULL,
    FEATURED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DATASET_FINGERPRINT VARCHAR,
    TARGET_SERIOUS_DLQIN_2YRS NUMBER(1,0),
    REVOLVING_UTILIZATION_CAPPED FLOAT,
    AGE_YEARS_CLEAN NUMBER(38,0),
    DELINQUENCY_30_59_CAPPED NUMBER(38,0),
    DEBT_RATIO_CAPPED FLOAT,
    MONTHLY_INCOME_IMPUTED FLOAT,
    MONTHLY_INCOME_MISSING_INDICATOR NUMBER(1,0),
    OPEN_CREDIT_LINES_AND_LOANS_COUNT NUMBER(38,0),
    TIMES_90_DAYS_LATE_CAPPED NUMBER(38,0),
    REAL_ESTATE_LOANS_OR_LINES_COUNT NUMBER(38,0),
    DELINQUENCY_60_89_CAPPED NUMBER(38,0),
    DEPENDENTS_COUNT_IMPUTED FLOAT,
    DEPENDENTS_MISSING_INDICATOR NUMBER(1,0),
    AGE_IMPLAUSIBLE_FLAG NUMBER(1,0),
    REVOLVING_UTILIZATION_GT_1_FLAG NUMBER(1,0),
    DEBT_RATIO_GT_5_FLAG NUMBER(1,0),
    DELINQUENCY_EXTREME_FLAG NUMBER(1,0)
)
COMMENT = 'Model-ready feature snapshots derived from curated credit risk cases with versioned schema and feature pipeline metadata.';
