-- Credit Risk Intelligence Platform
-- Stage 2 Snowflake foundation
-- Purpose: create SERVING-layer tables for predictions, model versions, and monitoring inputs.

USE DATABASE ML_RISK_CONTROL;
USE SCHEMA SERVING;

CREATE TABLE IF NOT EXISTS MODEL_PREDICTIONS (
    PREDICTION_ID VARCHAR NOT NULL,
    FEATURE_RECORD_ID VARCHAR NOT NULL,
    CURATED_RECORD_ID VARCHAR,
    SOURCE_ROW_ID NUMBER(38,0),
    INPUT_SOURCE_IDENTIFIER VARCHAR,
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    FEATURE_SCHEMA_VERSION VARCHAR NOT NULL,
    FEATURE_PIPELINE_VERSION VARCHAR,
    RAW_PROBABILITY FLOAT NOT NULL,
    CALIBRATED_PROBABILITY FLOAT,
    DECISION_THRESHOLD FLOAT NOT NULL,
    PREDICTED_LABEL NUMBER(1,0),
    RISK_BAND VARCHAR,
    DEMO_ACTION VARCHAR,
    EXPLANATION_SUMMARY VARCHAR,
    SCORED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Prediction audit records including model version, feature schema version, probabilities, threshold, and risk-band outputs.';

CREATE TABLE IF NOT EXISTS MODEL_VERSIONS (
    MODEL_VERSION_ID VARCHAR NOT NULL,
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    FEATURE_SCHEMA_VERSION VARCHAR NOT NULL,
    FEATURE_PIPELINE_VERSION VARCHAR,
    TRAINING_DATA_FINGERPRINT VARCHAR,
    PRIMARY_SELECTION_METRIC VARCHAR,
    PRIMARY_SELECTION_VALUE FLOAT,
    CALIBRATION_METHOD VARCHAR,
    DECISION_THRESHOLD FLOAT,
    RISK_BAND_POLICY_VERSION VARCHAR,
    ARTIFACT_URI VARCHAR,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    REGISTERED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Registered model versions and deployment-facing metadata for reproducible scoring and audit traceability.';

CREATE TABLE IF NOT EXISTS DATA_QUALITY_RUNS (
    DATA_QUALITY_RUN_ID VARCHAR NOT NULL,
    SOURCE_LAYER VARCHAR NOT NULL,
    SOURCE_OBJECT_NAME VARCHAR NOT NULL,
    DATASET_SPLIT VARCHAR,
    DATASET_FINGERPRINT VARCHAR,
    RULESET_VERSION VARCHAR NOT NULL,
    RUN_STATUS VARCHAR NOT NULL,
    ERROR_COUNT NUMBER(38,0) NOT NULL DEFAULT 0,
    WARNING_COUNT NUMBER(38,0) NOT NULL DEFAULT 0,
    ERROR_SUMMARY VARCHAR,
    WARNING_SUMMARY VARCHAR,
    EXECUTED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Validation and monitoring run summaries used to track data-quality outcomes across raw and curated processing stages.';
